{
 "title": "Money Transfer",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC Pause Duration",
   "type": "timeseries",
   "description": "Shows the average pause duration (in milliseconds) of GC cycles over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(go_gc_duration_seconds_sum[1m]) / rate(go_gc_duration_seconds_count[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "timeseries",
   "description": "Average CPU seconds used per second over the last 1 minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  { "title": "Http metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{url!~\"/metrics|/swagger/doc.json|/swagger/favicon-32x32.png|/swagger/index.html|/swagger/swagger-ui-bundle.js|/swagger/swagger-ui-standalone-preset.js|/swagger/swagger-ui.css\"}[1m])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "usage of /transfers endpoint",
   "type": "stat",
   "description": "usage of /transfers endpoint. Resets on restart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{url=\"/transfers\"}",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}