basePath: /
definitions:
  dtos.BalanceResponseDto:
    properties:
      balance:
        type: number
    type: object
  dtos.CreateTransactionResponseDto:
    properties:
      message:
        type: string
      status:
        type: string
      transaction_id:
        type: string
    type: object
  dtos.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  dtos.TransactionRequestDto:
    properties:
      amount:
        type: number
      from:
        type: string
      to:
        type: string
    type: object
  dtos.TransactionResponseDto:
    properties:
      transactions:
        items:
          $ref: '#/definitions/model.Transaction'
        type: array
    type: object
  model.Transaction:
    properties:
      amount:
        type: number
      created_at:
        type: string
      id:
        type: string
      receiver_id:
        type: string
      sender_id:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for transferring money between users
  title: Money Transfer API
  version: "1.0"
paths:
  /balance/{userId}:
    get:
      consumes:
      - application/json
      description: Get current balance for a specific user
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.BalanceResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Get user balance
      tags:
      - users
  /transfers:
    post:
      consumes:
      - application/json
      description: Create a new money transfer transaction
      parameters:
      - description: Transaction details
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/dtos.TransactionRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CreateTransactionResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Create new transaction
      tags:
      - transfers
  /transfers/{userId}:
    get:
      consumes:
      - application/json
      description: Get all transactions for a specific user
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.TransactionResponseDto'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Get transactions by user Id
      tags:
      - transfers
swagger: "2.0"
